services:
  db:
    image: postgres:16.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: skyline
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_ADDR: postgres://admin:adminpassword@db/skyline?sslmode=disable
    depends_on:
      - db

volumes:
  db-data:
